version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci  # Prefer npm ci for clean reproducible installs
  build:
    commands:
      - echo Building the project...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist  # <-- Vite outputs to dist, not build
  discard-paths: no
